name: Test Suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.1.4', '3.2']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: set up dotenv
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo $API_TOKEN | base64 --decode > .env
      - name: bundle install
        run: bundle install
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake test
